self-hosted-runner:
  # Labels of self-hosted runner in array of strings.
  labels: [ubuntu-22.04-arm, windows-2025]

# Configuration variables in array of strings defined in your repository or
# organization. `null` means disabling configuration variables check.
# Empty array means no configuration variable is allowed.
config-variables: null

# Configuration for file paths. The keys are glob patterns to match to file
# paths relative to the repository root. The values are the configurations for
# the file paths. Note that the path separator is always '/'.
# The following configurations are available.
#
# "ignore" is an array of regular expression patterns. Matched error messages
# are ignored. This is similar to the "-ignore" command line option.
# Path-specific configurations.

paths:
  # Match all workflow files
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      # SC2086 - Double quote to prevent globbing and word splitting
      - 'shellcheck reported issue in this script: SC2086:.+'
      
      # SC2046 - Quote this to prevent word splitting
      - 'shellcheck reported issue in this script: SC2046:.+'
      
      # SC2236 - Use -n instead of ! -z
      - 'shellcheck reported issue in this script: SC2236:.+'
      
      # SC1001 - Backslash interpretation warnings
      - 'shellcheck reported issue in this script: SC1001:.+'
      
      # SC2059 - printf format variables
      - 'shellcheck reported issue in this script: SC2059:.+'
      
      # SC2129 - Multiple redirects suggestion
      - 'shellcheck reported issue in this script: SC2129:.+'
      
      # SC2034 - Unused variable warning
      - 'shellcheck reported issue in this script: SC2034:.+'