name: Check YAML Files

on:
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: |
          pip install yamllint

      - name: Validate YAML Syntax
        run: |
          # Check syntax for any YAML files that changed in the PR
          yamllint $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.ya?ml$') || exit 1

      - name: Install actionlint
        uses: rhysd/actionlint@v1

      - name: Lint GitHub Workflow Files
        run: |
          # Lint only the GitHub workflow YAML files
          actionlint -color
