name: Lint YAML files

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install actionlint
        run: |
          curl -sSL "https://github.com/rhysd/actionlint/releases/latest/download/actionlint_linux_amd64.zip" -o actionlint.zip
          unzip actionlint.zip -d /usr/local/bin
          rm actionlint.zip

      - name: Lint YAML files
        run: |
          # Lint all yaml/yml files in the .github/workflows folder
          find .github/workflows -name '*.yml' -o -name '*.yaml' | xargs actionlint
