name: Lint GitHub Workflow YAML Files

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install actionlint
        run: |
          curl -sSL "https://github.com/rhysd/actionlint/releases/latest/download/actionlint_linux_amd64.zip" -o actionlint.zip
          unzip actionlint.zip -d /usr/local/bin
          rm actionlint.zip

      - name: Lint GitHub Workflow YAML Files with actionlint
        run: |
          # Run actionlint on all files in .github/workflows
          actionlint .github/workflows/*.yml .github/workflows/*.yaml
