name: Lint GitHub Workflow YAML Files

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

env:
  ACTIONLINT_VERSION: "1.7.3"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Workflows with Docker
        run: |
          echo "Starting workflow linting..."
          
          # Create actionlint config file with ignored errors
          cat << EOF > /tmp/actionlint-config.yaml
          ignore:
            # Ignore specific runner labels
            - 'label "ubuntu-22.04-arm" is unknown'
            - 'label "windows-2025" is unknown'
            
            # Ignore all SC2086 (unquoted variables) warnings
            - 'SC2086'
          EOF
          
          # Run actionlint with the config file
          docker run --rm \
            -v "${{ github.workspace }}:/repo" \
            -v "/tmp/actionlint-config.yaml:/actionlint-config.yaml" \
            --workdir /repo \
            rhysd/actionlint:${{ env.ACTIONLINT_VERSION }} \
            -config /actionlint-config.yaml \
            -color \
            .github/workflows/*.yml .github/workflows/*.yaml