# Validates all workflow files on PR changes

name: Lint Workflow Files
on:
  pull_request:
    paths:
      - '.github/workflows/**/*.yml'
      - '.github/workflows/**/*.yaml'

jobs:
  lint-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yamllint and codespell
        run: |
          pip install yamllint
          pip install codespell

      # Run the spell check first
      - name: Run Spell Check
        run: codespell .github/workflows/**/*.yml .github/workflows/**/*.yaml
        continue-on-error: false  
        
      # Run YAML syntax check only if spelling check passes
      - name: Run YAML syntax check
        if: success()
        run: yamllint .github/workflows/*.yml .github/workflows/*.yaml --config-file .github/workflows/.yamllint

      # Run Actions-specific checks only if YAML linting passes
      - name: Run Actions-specific checks
        if: success()
        uses: reviewdog/action-actionlint@v1

      - name: Reminder to Fix Errors
        if: failure()
        run: echo "Please ensure all spelling and linting errors are addressed before merging the pull request."

