name: Lint GitHub Workflow YAML Files

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools # Will install actionlint from go.mod
        run: make install-tools     
      
      - name: Check actionlint version
        run: actionlint -version
      
      - name: Run actionlint
        run: |
          actionlint \
            -ignore 'SC2086' \
            -ignore 'SC2046' \
            -ignore 'SC2059' \
            -ignore 'SC2236' \
            -ignore 'SC1001' \
            -ignore 'SC2129' \
            -color .github/workflows/*.yml .github/workflows/*.yaml

      - name: Reminder on failure
        if: failure()
        run: echo "⚠️ Please fix linting errors before merging."

      - name: Success message
        if: success()
        run: echo "✅ All workflow files are valid."