name: Lint GitHub Workflow YAML Files

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.24'
          cache: true

      - name: Run actionlint via Makefile
        run: |
          cd internal/tools
          go mod tidy
          go install github.com/rhysd/actionlint/cmd/actionlint@v1.7.3
          make install-tools

      - name: Lint GitHub Workflow YAML Files
        run: |
          actionlint \
            -config-file ./.github/actionlint.yaml \
            -color .github/workflows/*.yml .github/workflows/*.yaml

      - name: Reminder to Address Linting Errors
        if: failure()
        run: |
          echo "⚠️ Please address all linting errors before merging this pull request."

      - name: All linting checks passed
        if: success()
        run: |
          echo "✅ All linting checks passed."