name: Lint GitHub Workflow YAML Files

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

env:
  ACTIONLINT_VERSION: "1.7.3"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pre-pull Docker Image
        run: docker pull rhysd/actionlint:${{ env.ACTIONLINT_VERSION }}

      - name: Lint GitHub Workflow YAML Files with Docker
        run: |
          docker run --rm -v "${{ github.workspace }}:/repo" --workdir /repo rhysd/actionlint:${{ env.ACTIONLINT_VERSION }} \
            -ignore 'SC2086' \
            -ignore 'SC2046' \
            -ignore 'SC2059' \
            -ignore 'SC2236' \
            -ignore 'SC1001' \
            -color .github/workflows/*.yml .github/workflows/*.yaml

      - name: Reminder to Address Linting Errors
        if: failure()
        run: |
          echo "⚠️ Please address all linting errors before merging this pull request."

      - name: All linting checks passed
        if: success()
        run: |
          echo "✅ All linting checks passed."