name: Lint GitHub Workflow YAML Files

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.24'
          cache: true

      - name: Run actionlint via Makefile
        run: |
          cd internal/tools
          go mod tidy
          make actionlint

      - name: Lint GitHub Workflow YAML Files
        run: |
          actionlint \
            -ignore 'SC2086' \
            -ignore 'SC2046' \
            -ignore 'SC2059' \
            -ignore 'SC2236' \
            -ignore 'SC1001' \
            -ignore 'SC2129' \
            -color .github/workflows/*.yml .github/workflows/*.yaml

      - name: Reminder to Address Linting Errors
        if: failure()
        run: |
          echo "⚠️ Please address all linting errors before merging this pull request."

      - name: All linting checks passed
        if: success()
        run: |
          echo "✅ All linting checks passed."