# Validates all workflow files on PR changes

name: Lint Workflow Files
on:
  pull_request:
    paths:
      - '.github/workflows/**/*.yml'

jobs:
  lint-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip install yamllint

      - name: Run YAML syntax check
        run: yamllint .github/workflows/*.yml .github/workflows/*.yaml --config-file .github/workflows/.yamllint

      - name: Install codespell
        run: pip install codespell  # Install codespell for checking spelling errors

      - name: Run Spell Check
        run: codespell .github/workflows/**/*.yml  # Spell check for human errors

      - name: Run Actions-specific checks
        uses: reviewdog/action-actionlint@v1

      - name: Reminder to Fix Errors
        if: failure()
        run: echo "Please ensure all linting and spelling errors are addressed before merging the pull request."
